# this build and yaml are different from what is used by bioconda - this is for local building, not distribution

package:
    name: ampliconsuite
    version: 0.1555.2

source:
#    git_url: https://github.com/AmpliconSuite/AmpliconSuite-pipeline
    path: ../

build:
    number: 0

requirements:
    build:
        - python >=3
        - setuptools
        - unzip
        - wget

    run:
        - python >=3
        - bwa
        - cnvkit >=0.9.10
        - Flask
        - future
        - intervaltree
        - matplotlib-base
        - mscorefonts
        - numpy
        - pysam
        - samtools
        - scipy
        - pandas

test:
    commands:
    - AmpliconSuite-pipeline.py -v
    imports:
    - paalib
    - ampliconarchitectlib
    - ampliconclassifierlib

about:
    home: https://github.com/AmpliconSuite
    license: BSD 2-Clause License
    summary: An end-to-end wrapper for focal amplification analysis from whole-genome sequencing using AmpliconArchitect and associated tools.
