package:
    name: ampliconsuite
    version: 0.1546.1

source:
#    git_url: https://github.com/AmpliconSuite/AmpliconSuite-pipeline
    path: ../

build:
    number: 0
    skip: False

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - bwa
        - cnvkit
        - Flask
        - future>=0.18.3
        - intervaltree>=3.1.0
        - matplotlib>=3.5.1
        - mosek
        - numpy>=1.22.4
        - pysam
        - samtools
        - scipy>=1.7.3

test:
    commands:
    - AmpliconSuite-pipeline.py -v
    imports:
    - paalib
    - ampliconarchitectlib
    - ampliconclassifierlib
    - mosek

about:
    home: https://github.com/AmpliconSuite
    license: BSD 2-Clause License
    summary: An end-to-end wrapper for focal amplification analysis from whole-genome sequencing using AmpliconArchitect and associated tools.
